name: Data Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

jobs:
  dvf:
    uses: ./.github/workflows/dvf-pipeline.yml
    secrets: inherit

  filosofi:
    uses: ./.github/workflows/filosofi-pipeline.yml
    secrets: inherit
